"""
Django settings for linNote project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4oprie3!a7^%8igi^if!gwv6!_((2hmfytb5+z2%j$hwd5fa&r"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "blog.apps.BlogConfig",
    "linauth.apps.LinauthConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "linNote.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            # 加在这里
            "builtins": ["django.templatetags.static"],
        },
    },
]

WSGI_APPLICATION = "linNote.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Django 方式
STATICFILES_DIRS = [
    # 这个 static 可以变成 ABC 只是一个名称
    BASE_DIR
    / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# SMTP（Simple Mail Transfer Protocol，简单邮件传输协议）是互联网上用于发送电子邮件的核心通信协议。
# 发送邮件：将电子邮件从发件人传输到收件人的邮件服务器（如 QQ 邮箱、Gmail 等）。
# 不涉及接收邮件：接收邮件使用其他协议（如 POP3/IMAP）。

# 指定邮件后端实现，smtp.EmailBackend 表示使用 SMTP 协议发送邮件。
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# 是否启用 TLS 加密（推荐 True，端口 587 时必启用）。
EMAIL_USE_TLS = True
# SMTP 服务器地址，这里是 QQ 邮箱的服务器。
EMAIL_HOST = "smtp.qq.com"
# SMTP 服务器端口号，QQ 邮箱的 TLS 端口为 587（SSL 端口为 465）。
EMAIL_PORT = 587
# 发件人邮箱地址（需与 SMTP 服务器匹配）。
EMAIL_HOST_USER = "1909773034@qq.com"
# 授权码（非邮箱密码，需在邮箱设置中生成）。
EMAIL_HOST_PASSWORD = "dybllguwrfkabjfg"
# 默认发件人显示名称（可设为与 EMAIL_HOST_USER 相同）
DEFAULT_FROM_EMAIL = "1909773034@qq.com"


LOGIN_URL = "/auth/login"
